# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/145u5nmpYAtJiQePjuDYdEHPmmwDca9Lo
"""

from re import L
list1 = [2,4,6,8,10]
square = [i**2 for i in list1]
print('Square of the numbers are: ', square)
cube = [i**3 for i in list1]
print('Cube of the numbers are: ',cube)

